# Generated by Django 4.1.1 on 2022-09-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0005_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
