# Generated by Django 4.1.1 on 2022-09-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0011_remove_task_description_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank='True'),
        ),
    ]
